# Generated by Django 2.0.4 on 2018-04-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[(1, 'T'), (2, 'G'), (2, 'U'), (4, 'O')], default='U', max_length=2),
        ),
    ]
