# Generated by Django 2.0.4 on 2018-05-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0005_auto_20180506_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['bno']},
        ),
    ]
